services:
  web:
    build: ./web-app
    ports:
      - "5001:5001"
    depends_on:
      - ml
    env_file:
      - .env

  ml:
    build: ./machine-learning-client
    ports:
      - "6000:6000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
