name: ML Client CI

on:
  push:
    paths:
      - 'ml-client/**'
      - '.github/workflows/ml-client.yml'
      - 'docker-compose.yml'
  pull_request:
    paths:
      - 'machine-learning-client/**'
      - '.github/workflows/ml-client.yml'
      - 'docker-compose.yml'
      
jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and start ml-client container
        run: docker-compose up -d --build ml

      - name: Wait for ML client to be ready
        run: |
          echo "Waiting for ML client to start..."
          until curl -s http://localhost:6000 || [ $SECONDS -ge 60 ]; do sleep 2; done

      - name: Run tests inside ml-client container
        run: |
          docker-compose exec -T ml pytest /app/web-app-tests

      - name: Shut down containers
        run: docker-compose down
